In [1]:
pip install torch==1.3.1+cpu torchvision==0.4.2+cpu -f https://download.pytorch.org/whl/torch_stable.html

Looking in links: https://download.pytorch.org/whl/torch_stable.html
Note: you may need to restart the kernel to use updated packages.


In [2]:
import torch

In [3]:
a=torch.ones(5,3)
b=torch.ones(5,3)
print(a+b)

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])


In [4]:
a=torch.tensor([1.0,2.0])
out=a.pow(2).sum()
print(out)

tensor(5.)


In [6]:
a=torch.eye(5,5)
b=torch.ones(5,5)
c=a*b

In [7]:
c

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [8]:
torch.rot90(c)

tensor([[0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0.],
        [0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0.],
        [1., 0., 0., 0., 0.]])

In [9]:
torch.cuda.is_available()

False

In [11]:
%time
a=torch.rand(1000,1000)
b=torch.rand(1000,1000)
a.matmul(b)

Wall time: 0 ns


tensor([[252.0563, 251.6541, 242.8150,  ..., 251.0023, 250.9362, 257.7179],
        [261.8439, 258.3353, 245.0668,  ..., 251.5115, 254.9958, 265.3219],
        [256.5443, 250.1281, 238.8515,  ..., 245.6143, 251.6289, 258.1530],
        ...,
        [247.3002, 249.8864, 236.8502,  ..., 244.6031, 246.9569, 249.9539],
        [257.6913, 253.6913, 247.1457,  ..., 252.4833, 250.4903, 254.3654],
        [257.1260, 246.1889, 242.4796,  ..., 246.3406, 250.0781, 254.1862]])

In [12]:
y=torch.eye(5,5)
print(torch.mean(y))
chain_2=chain()
mean_y=chain_2(y)
print(mean_y)

tensor(0.2000)


NameError: name 'chain' is not defined

In [16]:
import torch.nn as nn
sample_x=torch.rand(64,60,100)
sig=nn.Sigmoid()
fc=nn.Linear(100,50)
out=fc(sample_x)
out1=sig(out)
print(out1.size())


torch.Size([64, 60, 50])


In [18]:
 m=nn.Softmax(dim=1)
x=torch.randn(4,5)
out=m(x)
print(out)

tensor([[0.2907, 0.0499, 0.1784, 0.1605, 0.3205],
        [0.0899, 0.6364, 0.1025, 0.1101, 0.0611],
        [0.3484, 0.0461, 0.0566, 0.0715, 0.4774],
        [0.1296, 0.0447, 0.0214, 0.2048, 0.5995]])


In [20]:
import torch
a=torch.tensor(2.0,reqires_grad=True)
b=torch.tensor(1.0,reqires_grad=True)
c=a+b
c.retain_grad()

TypeError: tensor() got an unexpected keyword argument 'reqires_grad'

In [22]:
 m=nn.Softmax(dim=-2)
x=torch.randn(4,5)
out=m(x)
print(out)

tensor([[0.3419, 0.1832, 0.1612, 0.4475, 0.2356],
        [0.0616, 0.1232, 0.0776, 0.2404, 0.3051],
        [0.4502, 0.0409, 0.5536, 0.0746, 0.3262],
        [0.1464, 0.6527, 0.2076, 0.2375, 0.1332]])


In [23]:
import matplotlib.pyplot as plt

In [24]:
import pickle

In [25]:
def convert_to_pickle(item,directory):
    pickle.dump(item,open(directory,'wb'))
def convert_to_pickle(directory):
    return pickle.load(open(directory,'rb'))

In [26]:
a=torch.tensor(1)
a.size()

torch.Size([])

In [27]:
a.type()

'torch.LongTensor'

In [28]:
b=torch.tensor([[0.1, 1.2], [2.2, 3.1], [4.9, 5.2]])

In [29]:
b

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])